export type Ap48Item = { id: number; text: string };
export const questions: Ap48Item[] = [
  {id:1, text:"Często czuję, że kontroluję swoje życie."},
  {id:2, text:"Kiedy mam problem, potrafię znaleźć rozwiązanie."},
  {id:3, text:"Ludzie uważają mnie za zorganizowaną osobę."},
  {id:4, text:"Łatwo dostosowuję się do zmian."},
  {id:5, text:"Podejmuję decyzje bez zbędnej zwłoki."},
  {id:6, text:"Potrafię wyznaczać sobie realistyczne cele."},
  {id:7, text:"Zwykle kończę to, co zacząłem."},
  {id:8, text:"Umiem zachować spokój pod presją."},
  {id:9, text:"Potrafię przyznać się do błędu."},
  {id:10, text:"Zazwyczaj potrafię przekonać innych do swoich racji."},
  {id:11, text:"Staram się patrzeć na sytuacje z różnych perspektyw."},
  {id:12, text:"Jestem wytrwały w dążeniu do celu."},
  {id:13, text:"Czuję się komfortowo pracując w zespole."},
  {id:14, text:"Umiem słuchać innych."},
  {id:15, text:"Zwracam uwagę na potrzeby innych ludzi."},
  {id:16, text:"Potrafię jasno komunikować swoje myśli."},
  {id:17, text:"Jestem empatyczny wobec innych."},
  {id:18, text:"Łatwo nawiązuję nowe znajomości."},
  {id:19, text:"Potrafię rozwiązywać konflikty."},
  {id:20, text:"Cenię współpracę bardziej niż rywalizację."},
  {id:21, text:"Umiem prosić o pomoc, gdy jej potrzebuję."},
  {id:22, text:"Chętnie dzielę się wiedzą."},
  {id:23, text:"Doceniam różnorodność opinii."},
  {id:24, text:"Czuję się częścią społeczności."},
  {id:25, text:"Potrafię analizować skomplikowane problemy."},
  {id:26, text:"Lubię uczyć się nowych rzeczy."},
  {id:27, text:"Myślę kreatywnie."},
  {id:28, text:"Stosuję różne strategie, aby osiągać cele."},
  {id:29, text:"Potrafię przewidywać konsekwencje działań."},
  {id:30, text:"Szybko orientuję się w nowych sytuacjach."},
  {id:31, text:"Umiem łączyć fakty z różnych dziedzin."},
  {id:32, text:"Często mam nowe pomysły."},
  {id:33, text:"Potrafię kwestionować utarte schematy."},
  {id:34, text:"Lubię eksperymentować."},
  {id:35, text:"Czuję satysfakcję z rozwiązywania zagadek."},
  {id:36, text:"Uczę się na błędach."},
  {id:37, text:"Dbam o swoje zdrowie fizyczne."},
  {id:38, text:"Regularnie odpoczywam i regeneruję siły."},
  {id:39, text:"Utrzymuję równowagę między pracą a życiem prywatnym."},
  {id:40, text:"Potrafię zarządzać stresem."},
  {id:41, text:"Przestrzegam zdrowej diety."},
  {id:42, text:"Dbam o aktywność fizyczną."},
  {id:43, text:"Potrafię odmawiać, gdy coś mi nie służy."},
  {id:44, text:"Dbam o higienę snu."},
  {id:45, text:"Unikam szkodliwych nawyków."},
  {id:46, text:"Regularnie badam swoje zdrowie."},
  {id:47, text:"Rozpoznaję sygnały przemęczenia."},
  {id:48, text:"Stawiam sobie realne wymagania."}
];